/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesExampleIdRouteImport } from './routes/examples/$exampleId'
import { Route as EmbedExampleIdRouteImport } from './routes/embed/$exampleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesExampleIdRoute = ExamplesExampleIdRouteImport.update({
  id: '/examples/$exampleId',
  path: '/examples/$exampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedExampleIdRoute = EmbedExampleIdRouteImport.update({
  id: '/embed/$exampleId',
  path: '/embed/$exampleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed/$exampleId': typeof EmbedExampleIdRoute
  '/examples/$exampleId': typeof ExamplesExampleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed/$exampleId': typeof EmbedExampleIdRoute
  '/examples/$exampleId': typeof ExamplesExampleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed/$exampleId': typeof EmbedExampleIdRoute
  '/examples/$exampleId': typeof ExamplesExampleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embed/$exampleId' | '/examples/$exampleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embed/$exampleId' | '/examples/$exampleId'
  id: '__root__' | '/' | '/embed/$exampleId' | '/examples/$exampleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedExampleIdRoute: typeof EmbedExampleIdRoute
  ExamplesExampleIdRoute: typeof ExamplesExampleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$exampleId': {
      id: '/examples/$exampleId'
      path: '/examples/$exampleId'
      fullPath: '/examples/$exampleId'
      preLoaderRoute: typeof ExamplesExampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$exampleId': {
      id: '/embed/$exampleId'
      path: '/embed/$exampleId'
      fullPath: '/embed/$exampleId'
      preLoaderRoute: typeof EmbedExampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedExampleIdRoute: EmbedExampleIdRoute,
  ExamplesExampleIdRoute: ExamplesExampleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
